services:
  #  lis-service:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/lis
  #      - SPRING_DATASOURCE_USERNAME=postgres
  #      - SPRING_DATASOURCE_PASSWORD=postgres

  #  postgres:
  #    image: "postgres:17"
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=postgres
  #      - POSTGRES_DB=lis

  rabbitmq:
    container_name: lis_rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
