networks:
  app_net:
    driver: bridge

services:
  rabbitmq:
    container_name: lis_rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"


  lis-service:
    container_name: lis
    build:
      context: /laboratory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.31.11:5432/lis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_RABBITMQ_HOST=rabbitmq  # Имя сервиса как хост
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq

  #  postgres:
  #    image: "postgres:17"
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=postgres
  #      - POSTGRES_DB=lis

  adapter-service:
    container_name: adapter
    build:
      context: /adapter
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq  # Имя сервиса как хост
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq


