## Security
@authCons = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiMiIsImV4cCI6MTc1NDA3NjAwMCwiaWF0IjoxNzU0MDQwMDAwLCJhdXRob3JpdGllcyI6WyJMQUJPUkFUT1JZIl19.PZOxfmXlFBxJU3d1pmPEhteDnut-c_Zfg1sbiuGidpzajgQ1cZWsD4ntcUc1xx-eSqoCdTy5pQxY8pz0El-cQr0O41fV4jvUWGgOSXZsYyP-za0Qk0IkkLNRtAM-GeqcwfdO-5fUeJjD2eL3wSAs5NdiTFUHcWxP8tDK9l1UP2Yx2XwKwjjHFx8eXHxW5XCYU9p_JrsnqF7hcajIaGoPt_5AdaPLTDBJ0V0AxaXhhDEeO_AqpYZuwnCSLiQnu3xxwmtTrl-EemeH3zBguUc6ksgs5i7YV0tn7_1yXaWHL2X08XCWe2HtIJnHYjcrCNoednBfPD8KEi8t7cOqBFiuuQ
@authLabAss = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoibGFiYXNzIiwiZXhwIjoxNzU0MDc5OTYyLCJpYXQiOjE3NTQwNDM5NjIsImF1dGhvcml0aWVzIjpbIkxBQk9SQVRPUlkiLCJMQUJfQVNTSVNUQU5UIl19.U3N_UKpR25cLi3Dk5AepUWJtyMxvha0pUjrIiWhN_8hZvzz96snCXmG-NOpGWXF2RoJq9lroyMuegftzE_Qm1O54P8Mf8ZD4EjTv38rKnNlNLHGHHtqY8xKdDccj9AV8dQSAgplt9ByaO9XP2b18XIkU1Gpd-CRiPpqz_br2YuSuJAKxDd_ZbU_USe3m73hU1ijaeHOtQG97LBDaUzwNnAHRamn7tDDJxOICdhlcY00XPZywEpAZk2AFJrYCyagGraObZ7pqfR3hg_cs-yWF0jXK0jDsK0a_jL0lRb9fqpiSqqgJouXVnbdtnvrR0nYDrNb_daHKtlVX03IBO31iGA
@authNurse = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoibnVyc2UiLCJleHAiOjE3NTQwNzk5MDQsImlhdCI6MTc1NDA0MzkwNCwiYXV0aG9yaXRpZXMiOlsiTEFCT1JBVE9SWSIsIk5VUlNFIl19.jdKzPf96OE2jF5EvjJWNuiUvySQGDvLQ1FuM3FmGn6CO5gvAgvSQuOJja1s3koV9vmoC4fhX1aiPeJFyyyLofhQOwj-X_8_KFl-EcVP4zL7mjOUEfEvr3GvzKis6hoC1SJdn7Xz6VvqaTQSt03g2HKwXg-wgtJxi_gD7xXfSYVLB3LEAWd7yfd-VXm0RTrjUKaTXeRoRu0q83w7Lkj2mrHprXWktsEuhgdbT7XSNShbqTy19BIo_Ww6KMzi9k39onUxmy_KkPnSdfoIDHAdPfAxeD9ftpl0kxoc8CmbmKbf_xSza64vIpA3LISgill8JoI8EjbzpwbclnJiqaM5xjA
@authDoc = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZG9jIiwiZXhwIjoxNzU0MDgyOTgwLCJpYXQiOjE3NTQwNDY5ODAsImF1dGhvcml0aWVzIjpbIkxBQk9SQVRPUlkiLCJET0NUT1IiXX0.ahOQ1WdW66HXFIFU---Hk4YWzdjTaa7d4T1OqppcdtQyLpv5hdi6Hicipa1g-bynQJSJhaD4o46Cnp-gAx3JVRO1cobfD354dAWBruFbJ2tc5tqLs5aFm4daLeysqmRtV_U8gESzjDgKBjo7Rv0E0msN-4yCylHa0RJmgB69aIMdNGsCuF9sE9gmqz4Ox2wZ7vyS3htuyKVe0zCmqP-GZAxIk_dwDsICszDjNeTXobuFFkH5QI_t8lpJvHtZyCc4iuePENS_5IvCiNf0K8Cr9EfuyL6w_yGWpyWKv-ksZoDTA0zZ38NkTmRbxIr1pTU586nvN8SWMSEYmVLWwpGlsw

## Респшен
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    # "login": "cons",
    # "login": "labass",
    # "login": "nurse",
    "login": "doc",
    "password": "123"
}


### список тестов
GET http://localhost:8080/api/testItem HTTP/1.1

### создание пациента
POST http://localhost:8080/api/patient HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authCons}}

{
    "firstName": "Артем",
    "middleName": "Антонович",
    "lastName": "Красильников",
    "birthday": "1989-08-11",
    "phone" : "+7(432)-55-125-53"
}

### поиск пациента по имени
GET http://localhost:8080/api/patient/Красильников HTTP/1.1
Authorization: Bearer {{authCons}}


### создание заказа
POST http://localhost:8080/api/order HTTP/1.1
Authorization: Bearer {{authCons}}
Content-Type: application/json

{
    "patientId": 100,
    "staffId": 2,
    "testItemIdList" : [3]
}

## кабинет медсестры
### список пациентов, ожидающих забора БМ
GET http://localhost:8080/api/nurse/order HTTP/1.1
Authorization: Bearer {{authNurse}}

### открыть конкретный заказ у медсестры
GET http://localhost:8080/api/nurse/order/100 HTTP/1.1
Authorization: Bearer {{authNurse}}

### заканчиваем забор БМ и обновляем статусы
PUT http://localhost:8080/api/nurse/order/100 HTTP/1.1
Authorization: Bearer {{authNurse}}


## лаборант
### сканирует ШК тары при получении и обновляем статусы
PUT http://localhost:8080/api/labAss/testTubeResult/0000000100 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### информация по таре
GET http://localhost:8080/api/testTubeResult/barcode/0000000100  HTTP/1.1
Authorization: Bearer {{authLabAss}}

### список всех ошибок при работе с тарой
GET http://localhost:8080/api/testTubeError HTTP/1.1
Authorization: Bearer {{authLabAss}}

### обновить ошибку для тары
PUT http://localhost:8080/api/testTubeResult/error HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authLabAss}}

{
    "id": 100,
    # "errorId": 11
    "errorId": null
}

## журнал тары по дате и статусу 
### Транспортировка
GET http://localhost:8080/api/testTubeResult/time/2025-07-24/status/2 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### в работе
GET http://localhost:8080/api/testTubeResult/time/2025-07-29/status/4 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### отработан
GET http://localhost:8080/api/testTubeResult/time/2025-07-29/status/5 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### для врача
GET http://localhost:8080/api/testTubeResult/status/4 HTTP/1.1
# Authorization: Bearer {{authLabAss}}
Authorization: Bearer {{authDoc}}


## список измерений
### для врача по ШК
GET http://localhost:8080/api/measurementResult/testTubeResult/0000000100 HTTP/1.1
Authorization: Bearer {{authDoc}}

### по заказу для ресепшена и ЛК
GET http://localhost:8080/api/measurementResult/order/100 HTTP/1.1
Authorization: Bearer {{authDoc}}

### динамика измерения для пациента
GET http://localhost:8080/api/measurementResult/patient/100/measurementItemId/26 HTTP/1.1
Authorization: Bearer {{authDoc}}


## список измерений
### подписание документа
PUT http://localhost:8080/api/doctor/order/barcode/0000000100 HTTP/1.1
Authorization: Bearer {{authDoc}}


### список заказов пациента
GET http://localhost:8080/api/order/patient/100 HTTP/1.1
Authorization: Bearer {{authCons}}
