## Security
@authCons = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiY29ucyIsImV4cCI6MTc1NDE1NDI5MywiaWF0IjoxNzU0MTE4MjkzLCJhdXRob3JpdGllcyI6WyJMQUJPUkFUT1JZIl19.Z3yX7xqPbv3c3z1vCvhpAEOJ9iCchweWeldODwpUpFqz62Z5_OOgjeQmfNko6k0CgMP9-VQv0zfU4krDr2H3SzQ78TVtxFvRFeeWFVTmWLgCupmvX9uBGpkPrpJ7CdKb-ggw8Gj5ElXvX-6aFOQb0WazIZj9C4kP0_dNuP0rf2g9fI9P4XcpaLOddNKU-eveIr7-9vJOoAfO7Fv9AV-kXBeEjXfeZFlk7ml8sG_rnUk9WtDvI3E6_jH17mAew_SUxzSZCFuqdK72yHM2Oj83wuAadEQSfY1_-KCjczw-ZXxXOxomIFp0KobAzyJz3-HhE0EN5E6Oh8ZtuPCt01LeQQ
@authLabAss = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoibGFiYXNzIiwiZXhwIjoxNzU0MTU0NTM2LCJpYXQiOjE3NTQxMTg1MzYsImF1dGhvcml0aWVzIjpbIkxBQk9SQVRPUlkiLCJMQUJfQVNTSVNUQU5UIl19.H-ZMl4_Z4XZaWI0cm4g99HywAtLO0oOp6SltTzwuyAgSAUBEVqf1xEEa1KSZQ8K5aqWGAQuWtZZ6ECPSMJM6xv6qXpVfrMGmPsdpCBVoG5HthcsUF8tqsS7zWsXoWkwvGoHcZKc4KAdPWOKhaIJ5IkYFqoHF73emKEk1OTCK7b02b3CCvmfnSQY9y7HZu-DCNX4JXcIDEpmk8eTlQIUDTfORpZUm5XId78qZ1ne20q6wF9-Ls7FgMyEn5ojm5nkj45FJrZrwFdYV_hP2h5WDw2QrjD9Ay-t9UV0B1YNHCZSi6P7W5Sp_otWH76RarR0XNKTLbb9sNjCX2spNyYl9Fw
@authNurse = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoibnVyc2UiLCJleHAiOjE3NTQxNTQ0NjEsImlhdCI6MTc1NDExODQ2MSwiYXV0aG9yaXRpZXMiOlsiTEFCT1JBVE9SWSIsIk5VUlNFIl19.PdtMOL58Po72pruUhGv_VJZfdiLHl_502yQtBq0o9R7ii2hyViqXQYCuqcpqLVBw47zMNNho5fr3HvHaGF8jkOdQIInPxTPM3xp4q2w3awNEsqThIP9C7S5jKIL1Hw9_rhZaLSpl-fY9m15N18cjhsfjh_YAKc7v47geeIJ9wCyy1ppcRwOQFUytswCpCF-tJurO6k3UKV0SFo3vPTjdNxM_0ccO4btl-7cL-NIzBMzuvkxGUdj1qLU7j2LMrs7zRy8pcYpgHZcLo-VvbQHU12p_H7akYjfHOb0SmUOAkbnqdcxXnA43XDlK3o_Xr5oeiMub-aWU_FjfcUDxgfegIA
@authDoc = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZG9jIiwiZXhwIjoxNzU0MTU0ODI5LCJpYXQiOjE3NTQxMTg4MjksImF1dGhvcml0aWVzIjpbIkxBQk9SQVRPUlkiLCJET0NUT1IiXX0.DRPH37DtLMUN38uTryMAh5ye-L0nvp53q-yH-RnRV2zNn_KdbtM4dJ2Zf-ku1djJ4AzbCZpvEQAEYnxlT6epC1CMVFNKQyJD_Synwpu07bwypBG39p6LvuOln4XuDIIxzN_L1M87GjR7j_YPytFVIyn4O7akqhuLinUdOXFromdVFWfuN1nI-7qBe6HPclCSdCsd8B_JpILV7vqecd4nWqr1udlrcCF2fsTJ3Kco7evKqNpWUfR9reocXqX8Yu7hMpu9QAbJ9b1MUH9sT36GzYdHDMUxamlTUV877WVuV2biDN-PHVedXUdmGtM8rHuGbmUxFPW90U4HZf_F3iNkpg

## Респшен
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    # "login": "cons",
    # "login": "labass",
    # "login": "nurse",
    "login": "doc",
    "password": "123"
}


### список тестов
GET http://localhost:8080/api/testItem HTTP/1.1

### создание пациента
POST http://localhost:8080/api/patient HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authCons}}

{
    "firstName": "Артем",
    "middleName": "Антонович",
    "lastName": "Красильников",
    "birthday": "1989-08-11",
    "phone" : "+7(000)-00-000-00"
}

### поиск пациента по имени
GET http://localhost:8080/api/patient/Пирог HTTP/1.1
Authorization: Bearer {{authCons}}


### создание заказа
POST http://localhost:8080/api/order HTTP/1.1
Authorization: Bearer {{authCons}}
Content-Type: application/json

{
    "patientId": 100,
    "staffId": 2,
    "testItemIdList" : [3, 4]
}

## кабинет медсестры
### список пациентов, ожидающих забора БМ
GET http://localhost:8080/api/nurse/order HTTP/1.1
Authorization: Bearer {{authNurse}}

### открыть конкретный заказ у медсестры
GET http://localhost:8080/api/nurse/order/100 HTTP/1.1
Authorization: Bearer {{authNurse}}

### заканчиваем забор БМ и обновляем статусы
PUT http://localhost:8080/api/nurse/order/100 HTTP/1.1
Authorization: Bearer {{authNurse}}


## лаборант
### сканирует ШК тары при получении и обновляем статусы
PUT http://localhost:8080/api/labAss/testTubeResult/0000000100 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### информация по таре
GET http://localhost:8080/api/testTubeResult/barcode/0000000100  HTTP/1.1
Authorization: Bearer {{authNurse}}

### список всех ошибок при работе с тарой
GET http://localhost:8080/api/testTubeError HTTP/1.1
Authorization: Bearer {{authLabAss}}

### обновить ошибку для тары
PUT http://localhost:8080/api/testTubeResult/error HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authLabAss}}

{
    "id": 100,
    "errorId": 51
    # "errorId": null
}

## журнал тары по дате и статусу 
### Транспортировка
GET http://localhost:8080/api/testTubeResult/time/2025-08-02/status/2 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### в работе
GET http://localhost:8080/api/testTubeResult/time/2025-08-02/status/4 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### отработан
GET http://localhost:8080/api/testTubeResult/time/2025-08-02/status/5 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### ошибки
GET http://localhost:8080/api/testTubeResult/status/8 HTTP/1.1
Authorization: Bearer {{authLabAss}}

### для врача
GET http://localhost:8080/api/testTubeResult/status/4 HTTP/1.1
# Authorization: Bearer {{authLabAss}}
Authorization: Bearer {{authDoc}}


## список измерений
### для врача по ШК
GET http://localhost:8080/api/measurementResult/testTubeResult/0000000100 HTTP/1.1
Authorization: Bearer {{authDoc}}

### по заказу для ресепшена и ЛК
GET http://localhost:8080/api/measurementResult/order/100 HTTP/1.1
Authorization: Bearer {{authDoc}}

### динамика измерения для пациента
GET http://localhost:8080/api/measurementResult/patient/100/measurementItemId/26 HTTP/1.1
Authorization: Bearer {{authDoc}}


## список измерений
### подписание документа
PUT http://localhost:8080/api/doctor/order/barcode/0000000100 HTTP/1.1
Authorization: Bearer {{authDoc}}


### список заказов пациента
GET http://localhost:8080/api/order/patient/100 HTTP/1.1
Authorization: Bearer {{authCons}}
